/**
 * AgentFactory — TypeScript wrapper
 *
 * Re-exports the Tact-generated wrapper from contracts/build/AgentFactory/.
 * Build artifacts are generated by running:
 *   npx tact --config tact.config.json
 *
 * Additional opcodes and types from the hand-written layer are preserved here
 * for callers that depend on them.
 */

export * from '../build/AgentFactory/AgentFactory_AgentFactory';
