/**
 * AgentWallet — TypeScript wrapper
 *
 * Re-exports the Tact-generated wrapper from contracts/build/AgentWallet/.
 * Build artifacts are generated by running:
 *   npx tact --config tact.config.json
 */

export * from '../build/AgentWallet/AgentWallet_AgentWallet';
