/**
 * StrategyExecutor — TypeScript wrapper
 *
 * Re-exports the Tact-generated wrapper from contracts/build/StrategyExecutor/.
 * Build artifacts are generated by running:
 *   npx tact --config tact.config.json
 */

export * from '../build/StrategyExecutor/StrategyExecutor_StrategyExecutor';
