import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'core/index': 'core/index.ts',
    'core/ai/index': 'core/ai/index.ts',
    'core/ai-safety/index': 'core/ai-safety/index.ts',
    'core/security/index': 'core/security/index.ts',
    'core/plugins/index': 'core/plugins/index.ts',
    'core/multi-agent/index': 'core/multi-agent/index.ts',
    'core/protocol/index': 'core/protocol/index.ts',
    'core/protocol-constitution/index': 'core/protocol-constitution/index.ts',
    'core/risk-engine/index': 'core/risk-engine/index.ts',
    'core/runtime/index': 'core/runtime/index.ts',
    'core/agents/runtime/index': 'core/agents/runtime/index.ts',
    'core/agents/agent-runtime/index': 'core/agents/agent-runtime/index.ts',
    'core/agents/orchestrator/index': 'core/agents/orchestrator/index.ts',
    'core/agents/lifecycle/index': 'core/agents/lifecycle/index.ts',
    'core/strategies/engine/index': 'core/strategies/engine/index.ts',
    'core/strategies/strategy-engine/index': 'core/strategies/strategy-engine/index.ts',
    'core/strategies/marketplace/index': 'core/strategies/marketplace/index.ts',
    'core/strategies/backtesting/index': 'core/strategies/backtesting/index.ts',
    'core/market-data/base/index': 'core/market-data/base/index.ts',
    'core/market-data/data-platform/index': 'core/market-data/data-platform/index.ts',
    'core/portfolio/base/index': 'core/portfolio/base/index.ts',
    'core/portfolio/analytics/index': 'core/portfolio/analytics/index.ts',
    'core/trading/base/index': 'core/trading/base/index.ts',
    'core/trading/engine/index': 'core/trading/engine/index.ts',
    'core/trading/live/index': 'core/trading/live/index.ts',
    'core/agent/memory': 'core/agent/memory.ts',
  },
  outDir: 'dist',
  format: ['cjs', 'esm'],
});
