/**
 * AgentWallet — Blueprint / ton-sandbox tests
 *
 * These tests cover the AgentWallet Tact contract defined in
 * contracts/agent-wallet.tact.  They are designed to run inside the
 * Blueprint test framework (https://github.com/ton-org/blueprint) which
 * provides a local TVM sandbox that executes real TON cells.
 *
 * Run (once Blueprint is installed):
 *   npx blueprint test contracts/tests/agent-wallet.spec.ts
 *
 * Note: the contract must be compiled first:
 *   npx blueprint build agent-wallet
 *
 * The test file follows the standard Blueprint pattern but is kept
 * self-contained so it can also serve as documentation for the expected
 * contract behaviour.
 */

import { Blockchain, SandboxContract, TreasuryWallet } from '@ton/sandbox';
import { toNano, Address, fromNano } from '@ton/core';
import { AgentWallet } from '../wrappers/AgentWallet';  // generated by Blueprint build
import '@ton/test-utils';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ONE_TON = toNano('1');
const HALF_TON = toNano('0.5');
const MIN_RESERVE = toNano('0.05');

describe('AgentWallet', () => {
  let blockchain: Blockchain;
  let owner: SandboxContract<TreasuryWallet>;
  let agent: SandboxContract<TreasuryWallet>;
  let attacker: SandboxContract<TreasuryWallet>;
  let wallet: SandboxContract<AgentWallet>;

  beforeEach(async () => {
    blockchain = await Blockchain.create();

    owner    = await blockchain.treasury('owner');
    agent    = await blockchain.treasury('agent');
    attacker = await blockchain.treasury('attacker');

    wallet = blockchain.openContract(
      await AgentWallet.fromInit(
        owner.address,
        agent.address,
        owner.address,        // safeAddress = owner for tests
        toNano('10'),         // maxTradeSizeNano = 10 TON
        toNano('50'),         // dailyLimitNano  = 50 TON
        0                     // timeLockSeconds = 0 (no lock in tests)
      )
    );

    // Deploy the contract and fund it with 100 TON
    const deployResult = await wallet.send(
      owner.getSender(),
      { value: toNano('100') },
      { $$type: 'Deposit' }
    );
    expect(deployResult.transactions).toHaveTransaction({
      from: owner.address,
      to: wallet.address,
      deploy: true,
      success: true,
    });
  });

  // ---- Basic state ----

  it('should initialise with correct parameters', async () => {
    expect(await wallet.getPaused()).toBe(false);
    const [maxTrade, daily, timeLock] = await wallet.getLimits();
    expect(maxTrade).toBe(toNano('10'));
    expect(daily).toBe(toNano('50'));
    expect(timeLock).toBe(0n);
  });

  // ---- Deposit ----

  it('should accept TON deposits', async () => {
    const balanceBefore = await wallet.getBalance();
    await wallet.send(
      owner.getSender(),
      { value: ONE_TON },
      { $$type: 'Deposit' }
    );
    const balanceAfter = await wallet.getBalance();
    // Balance increases by approximately 1 TON (minus gas)
    expect(balanceAfter).toBeGreaterThan(balanceBefore);
  });

  it('should accept plain TON transfers', async () => {
    const balanceBefore = await wallet.getBalance();
    await owner.send({ to: wallet.address, value: ONE_TON });
    const balanceAfter = await wallet.getBalance();
    expect(balanceAfter).toBeGreaterThan(balanceBefore);
  });

  // ---- Owner withdraw (no time-lock) ----

  it('owner can withdraw immediately when timeLock is 0', async () => {
    const ownerBalanceBefore = await owner.getBalance();
    const result = await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: owner.address, amount: ONE_TON }
    );
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: owner.address,
      success: true,
    });
    const ownerBalanceAfter = await owner.getBalance();
    expect(ownerBalanceAfter).toBeGreaterThan(ownerBalanceBefore - toNano('0.1'));
  });

  it('non-owner cannot withdraw', async () => {
    const result = await wallet.send(
      attacker.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: attacker.address, amount: ONE_TON }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  // ---- Agent execute ----

  it('agent can execute a trade within limits', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('5'),
        payload: null,
        opCode: 0x1234,
      }
    );
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: target.address,
      success: true,
    });
  });

  it('agent cannot exceed maxTradeSize', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('15'),  // > maxTradeSizeNano (10 TON)
        payload: null,
        opCode: 0x1234,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  it('non-agent cannot call AgentExecute', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      attacker.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x0,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  it('agent is blocked when wallet is paused', async () => {
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetPaused', paused: true }
    );
    expect(await wallet.getPaused()).toBe(true);

    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x0,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  // ---- Daily limit ----

  it('agent cannot exceed daily limit', async () => {
    const target = await blockchain.treasury('dex');

    // 5 trades × 10 TON = 50 TON (hits the daily limit)
    for (let i = 0; i < 5; i++) {
      const r = await wallet.send(
        agent.getSender(),
        { value: toNano('0.05') },
        {
          $$type: 'AgentExecute',
          to: target.address,
          amount: toNano('10'),
          payload: null,
          opCode: i,
        }
      );
      expect(r.transactions).toHaveTransaction({ success: true });
    }

    // 6th trade should fail — daily limit exhausted
    const overflow = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 99,
      }
    );
    expect(overflow.transactions).toHaveTransaction({ success: false });
  });

  // ---- DEX whitelist ----

  it('agent is blocked by DEX whitelist', async () => {
    const allowedDex   = await blockchain.treasury('allowed_dex');
    const blockedDex   = await blockchain.treasury('blocked_dex');

    // Add allowedDex to whitelist
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetAllowedDex', dex: allowedDex.address, allowed: true }
    );

    // Trade to allowed DEX — succeeds
    const okResult = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: allowedDex.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x1,
      }
    );
    expect(okResult.transactions).toHaveTransaction({ success: true });

    // Trade to blocked DEX — fails
    const badResult = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: blockedDex.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x2,
      }
    );
    expect(badResult.transactions).toHaveTransaction({ success: false });
  });

  // ---- Update limits ----

  it('owner can update spending limits', async () => {
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'UpdateLimits',
        maxTradeSizeNano: toNano('20'),
        dailyLimitNano: toNano('100'),
        timeLockSeconds: 0,
      }
    );
    const [maxTrade, daily] = await wallet.getLimits();
    expect(maxTrade).toBe(toNano('20'));
    expect(daily).toBe(toNano('100'));
  });

  it('owner can change agent address', async () => {
    const newAgent = await blockchain.treasury('new_agent');
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetAgent', agent: newAgent.address }
    );
    expect(await wallet.getAgentAddress()).toEqualAddress(newAgent.address);
  });

  // ---- Emergency drain ----

  it('owner can emergency drain the wallet', async () => {
    const safeBalanceBefore = await owner.getBalance();
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'EmergencyDrain' }
    );
    expect(await wallet.getPaused()).toBe(true);
    const safeBalanceAfter = await owner.getBalance();
    // Safe address (owner) should have received the drained funds
    expect(safeBalanceAfter).toBeGreaterThan(safeBalanceBefore);
  });

  // ---- Time-lock withdrawals ----

  it('large withdrawals are time-locked', async () => {
    // Re-deploy with 60-second time-lock
    const lockedWallet = blockchain.openContract(
      await AgentWallet.fromInit(
        owner.address,
        agent.address,
        owner.address,
        toNano('10'),
        toNano('50'),
        60           // 60-second time-lock
      )
    );
    await lockedWallet.send(
      owner.getSender(),
      { value: toNano('20') },
      { $$type: 'Deposit' }
    );

    // Large withdrawal (> maxTradeSizeNano) should be queued
    const result = await lockedWallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: owner.address, amount: toNano('15') }
    );
    // The transaction itself succeeds (queued), but no outbound transfer yet
    expect(result.transactions).toHaveTransaction({
      from: owner.address,
      to: lockedWallet.address,
      success: true,
    });

    // Attempting to claim immediately should fail (time-lock not expired)
    const earlyClaimResult = await lockedWallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'ClaimWithdrawal', nonce: 1n }
    );
    expect(earlyClaimResult.transactions).toHaveTransaction({ success: false });
  });
});
