/**
 * AgentWallet — Blueprint / ton-sandbox tests
 *
 * These tests cover the AgentWallet Tact contract defined in
 * contracts/agent-wallet.tact.  They are designed to run inside the
 * Blueprint test framework (https://github.com/ton-org/blueprint) which
 * provides a local TVM sandbox that executes real TON cells.
 *
 * Run (once Blueprint is installed):
 *   npx blueprint test contracts/tests/agent-wallet.spec.ts
 *
 * Note: the contract must be compiled first:
 *   npx blueprint build agent-wallet
 *
 * The test file follows the standard Blueprint pattern but is kept
 * self-contained so it can also serve as documentation for the expected
 * contract behaviour.
 */

import { Blockchain, SandboxContract, TreasuryContract } from '@ton/sandbox';
import { toNano, Address, fromNano } from '@ton/core';
import { AgentWallet } from '../wrappers/AgentWallet';  // generated by Blueprint build
import '@ton/test-utils';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ONE_TON = toNano('1');
const HALF_TON = toNano('0.5');
const MIN_RESERVE = toNano('0.05');

describe('AgentWallet', () => {
  let blockchain: Blockchain;
  let owner: SandboxContract<TreasuryContract>;
  let agent: SandboxContract<TreasuryContract>;
  let attacker: SandboxContract<TreasuryContract>;
  let wallet: SandboxContract<AgentWallet>;

  beforeEach(async () => {
    blockchain = await Blockchain.create();

    owner    = await blockchain.treasury('owner');
    agent    = await blockchain.treasury('agent');
    attacker = await blockchain.treasury('attacker');

    wallet = blockchain.openContract(
      await AgentWallet.fromInit(
        owner.address,
        agent.address,
        owner.address,        // safeAddress = owner for tests
        toNano('10'),         // maxTradeSizeNano = 10 TON
        toNano('50'),         // dailyLimitNano  = 50 TON
        0n                    // timeLockSeconds = 0 (no lock in tests)
      )
    );

    // Deploy the contract and fund it with 100 TON
    const deployResult = await wallet.send(
      owner.getSender(),
      { value: toNano('100') },
      { $$type: 'Deposit' }
    );
    expect(deployResult.transactions).toHaveTransaction({
      from: owner.address,
      to: wallet.address,
      deploy: true,
      success: true,
    });
  });

  // ---- Basic state ----

  it('should initialise with correct parameters', async () => {
    expect(await wallet.getPaused()).toBe(false);
    const limits = await wallet.getLimits();
    expect(limits.maxTradeSizeNano).toBe(toNano('10'));
    expect(limits.dailyLimitNano).toBe(toNano('50'));
    expect(limits.timeLockSeconds).toBe(0n);
  });

  // ---- Deposit ----

  it('should accept TON deposits', async () => {
    const balanceBefore = await wallet.getBalance();
    await wallet.send(
      owner.getSender(),
      { value: ONE_TON },
      { $$type: 'Deposit' }
    );
    const balanceAfter = await wallet.getBalance();
    // Balance increases by approximately 1 TON (minus gas)
    expect(balanceAfter).toBeGreaterThan(balanceBefore);
  });

  it('should accept plain TON transfers', async () => {
    const balanceBefore = await wallet.getBalance();
    await owner.send({ to: wallet.address, value: ONE_TON });
    const balanceAfter = await wallet.getBalance();
    expect(balanceAfter).toBeGreaterThan(balanceBefore);
  });

  // ---- Owner withdraw (no time-lock) ----

  it('owner can withdraw immediately when timeLock is 0', async () => {
    const ownerBalanceBefore = await owner.getBalance();
    const result = await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: owner.address, amount: ONE_TON }
    );
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: owner.address,
      success: true,
    });
    const ownerBalanceAfter = await owner.getBalance();
    expect(ownerBalanceAfter).toBeGreaterThan(ownerBalanceBefore - toNano('0.1'));
  });

  it('non-owner cannot withdraw', async () => {
    const result = await wallet.send(
      attacker.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: attacker.address, amount: ONE_TON }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  // ---- Agent execute ----

  it('agent can execute a trade within limits', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('5'),
        payload: null,
        opCode: 0x1234n,
      }
    );
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: target.address,
      success: true,
    });
  });

  it('agent cannot exceed maxTradeSize', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('15'),  // > maxTradeSizeNano (10 TON)
        payload: null,
        opCode: 0x1234n,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  it('non-agent cannot call AgentExecute', async () => {
    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      attacker.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x0n,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  it('agent is blocked when wallet is paused', async () => {
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetPaused', paused: true }
    );
    expect(await wallet.getPaused()).toBe(true);

    const target = await blockchain.treasury('dex');
    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x0n,
      }
    );
    expect(result.transactions).toHaveTransaction({ success: false });
  });

  // ---- Daily limit ----

  it('agent cannot exceed daily limit', async () => {
    const target = await blockchain.treasury('dex');

    // 5 trades × 10 TON = 50 TON (hits the daily limit)
    for (let i = 0; i < 5; i++) {
      const r = await wallet.send(
        agent.getSender(),
        { value: toNano('0.05') },
        {
          $$type: 'AgentExecute',
          to: target.address,
          amount: toNano('10'),
          payload: null,
          opCode: BigInt(i),
        }
      );
      expect(r.transactions).toHaveTransaction({ success: true });
    }

    // 6th trade should fail — daily limit exhausted
    const overflow = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: toNano('1'),
        payload: null,
        opCode: 99n,
      }
    );
    expect(overflow.transactions).toHaveTransaction({ success: false });
  });

  // ---- DEX whitelist ----

  it('agent is blocked by DEX whitelist', async () => {
    const allowedDex   = await blockchain.treasury('allowed_dex');
    const blockedDex   = await blockchain.treasury('blocked_dex');

    // Add allowedDex to whitelist
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetAllowedDex', dex: allowedDex.address, allowed: true }
    );

    // Trade to allowed DEX — succeeds
    const okResult = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: allowedDex.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x1n,
      }
    );
    expect(okResult.transactions).toHaveTransaction({ success: true });

    // Trade to blocked DEX — fails
    const badResult = await wallet.send(
      agent.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'AgentExecute',
        to: blockedDex.address,
        amount: toNano('1'),
        payload: null,
        opCode: 0x2n,
      }
    );
    expect(badResult.transactions).toHaveTransaction({ success: false });
  });

  // ---- LOGIC-03: over-send / limit-bypass regression ----
  //
  // In Tact/TON, SendRemainingValue forwards the leftover inbound message
  // value *in addition to* the explicit `value`. The handlers previously
  // combined `value: msg.amount` with `SendRemainingValue`, so a caller could
  // attach a large inbound value and push far more TON to the target than
  // `maxTradeSizeNano` / `dailyLimitNano` (and the withdrawal balance check)
  // authorised. The fix sends exactly `msg.amount` with
  // `SendIgnoreErrors | SendPayGasSeparately` (no SendRemainingValue).

  it('AgentExecute sends exactly msg.amount even with large inbound value', async () => {
    const target = await blockchain.treasury('dex');
    const tradeAmount = toNano('5');

    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('30') },   // huge inbound value — would ride along via SendRemainingValue
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: tradeAmount,
        payload: null,
        opCode: 0x1234n,
      }
    );

    // The outbound message to the target must carry exactly the trade amount,
    // not msg.amount + leftover inbound value.
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: target.address,
      success: true,
      value: tradeAmount,
    });
  });

  it('AgentExecute does not let inbound value bypass maxTradeSize on the wire', async () => {
    const target = await blockchain.treasury('dex');
    const tradeAmount = toNano('10');   // == maxTradeSizeNano

    const result = await wallet.send(
      agent.getSender(),
      { value: toNano('40') },   // attempt to push 50 TON to the target
      {
        $$type: 'AgentExecute',
        to: target.address,
        amount: tradeAmount,
        payload: null,
        opCode: 0x1234n,
      }
    );

    // Exactly maxTradeSize leaves the wallet; the extra inbound value stays put.
    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: target.address,
      success: true,
      value: tradeAmount,
    });
    // No outbound transfer to the target should exceed the per-trade cap.
    expect(result.transactions).not.toHaveTransaction({
      from: wallet.address,
      to: target.address,
      value: (v) => v !== undefined && v > toNano('10'),
    });
  });

  it('WithdrawRequest sends exactly the requested amount regardless of inbound value', async () => {
    const recipient = await blockchain.treasury('withdraw_dest');
    const amount = toNano('3');

    const result = await wallet.send(
      owner.getSender(),
      { value: toNano('20') },   // large inbound value attached to the request
      { $$type: 'WithdrawRequest', to: recipient.address, amount }
    );

    expect(result.transactions).toHaveTransaction({
      from: wallet.address,
      to: recipient.address,
      success: true,
      value: amount,
    });
  });

  it('ClaimWithdrawal sends exactly the queued amount regardless of inbound value', async () => {
    // Wallet with a time-lock so the withdrawal is queued, then claimed.
    const lockedWallet = blockchain.openContract(
      await AgentWallet.fromInit(
        owner.address,
        agent.address,
        owner.address,
        toNano('10'),
        toNano('50'),
        60n
      )
    );
    await lockedWallet.send(
      owner.getSender(),
      { value: toNano('40') },
      { $$type: 'Deposit' }
    );

    const recipient = await blockchain.treasury('claim_dest');
    const amount = toNano('15');   // > maxTradeSize -> queued under time-lock

    await lockedWallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: recipient.address, amount }
    );

    // Fast-forward past the time-lock.
    blockchain.now = Math.floor(Date.now() / 1000) + 120;

    const claim = await lockedWallet.send(
      owner.getSender(),
      { value: toNano('20') },   // large inbound value on the claim
      { $$type: 'ClaimWithdrawal', nonce: 1n }
    );

    expect(claim.transactions).toHaveTransaction({
      from: lockedWallet.address,
      to: recipient.address,
      success: true,
      value: amount,
    });
  });

  // ---- Update limits ----

  it('owner can update spending limits', async () => {
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      {
        $$type: 'UpdateLimits',
        maxTradeSizeNano: toNano('20'),
        dailyLimitNano: toNano('100'),
        timeLockSeconds: 0n,
      }
    );
    const limits = await wallet.getLimits();
    expect(limits.maxTradeSizeNano).toBe(toNano('20'));
    expect(limits.dailyLimitNano).toBe(toNano('100'));
  });

  it('owner can change agent address', async () => {
    const newAgent = await blockchain.treasury('new_agent');
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'SetAgent', agent: newAgent.address }
    );
    expect(await wallet.getAgentAddress()).toEqualAddress(newAgent.address);
  });

  // ---- Emergency drain ----

  it('owner can emergency drain the wallet', async () => {
    const safeBalanceBefore = await owner.getBalance();
    await wallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'EmergencyDrain' }
    );
    expect(await wallet.getPaused()).toBe(true);
    const safeBalanceAfter = await owner.getBalance();
    // Safe address (owner) should have received the drained funds
    expect(safeBalanceAfter).toBeGreaterThan(safeBalanceBefore);
  });

  // ---- Time-lock withdrawals ----

  it('large withdrawals are time-locked', async () => {
    // Re-deploy with 60-second time-lock
    const lockedWallet = blockchain.openContract(
      await AgentWallet.fromInit(
        owner.address,
        agent.address,
        owner.address,
        toNano('10'),
        toNano('50'),
        60n          // 60-second time-lock
      )
    );
    await lockedWallet.send(
      owner.getSender(),
      { value: toNano('20') },
      { $$type: 'Deposit' }
    );

    // Large withdrawal (> maxTradeSizeNano) should be queued
    const result = await lockedWallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'WithdrawRequest', to: owner.address, amount: toNano('15') }
    );
    // The transaction itself succeeds (queued), but no outbound transfer yet
    expect(result.transactions).toHaveTransaction({
      from: owner.address,
      to: lockedWallet.address,
      success: true,
    });

    // Attempting to claim immediately should fail (time-lock not expired)
    const earlyClaimResult = await lockedWallet.send(
      owner.getSender(),
      { value: toNano('0.05') },
      { $$type: 'ClaimWithdrawal', nonce: 1n }
    );
    expect(earlyClaimResult.transactions).toHaveTransaction({ success: false });
  });
});
