<?php
/**
 * TON AI Agent - One-Click Installer
 *
 * This installer helps you set up TON AI Agent on your server.
 * IMPORTANT: Delete this file after successful installation!
 */

// Prevent caching
header('Cache-Control: no-store, no-cache, must-revalidate');
header('Pragma: no-cache');

// Error reporting
error_reporting(E_ALL);
ini_set('display_errors', '1');

session_start();

// Installation steps
$steps = [
    1 => 'Requirements Check',
    2 => 'Database Setup',
    3 => 'Configuration',
    4 => 'Telegram Bot',
    5 => 'Complete',
];

$currentStep = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = $_SESSION['error'] ?? null;
$success = $_SESSION['success'] ?? null;
unset($_SESSION['error'], $_SESSION['success']);

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    switch ($currentStep) {
        case 2:
            handleDatabaseSetup();
            break;
        case 3:
            handleConfiguration();
            break;
        case 4:
            handleTelegramSetup();
            break;
    }
}

function handleDatabaseSetup(): void
{
    $host = trim($_POST['db_host'] ?? '');
    $port = (int)($_POST['db_port'] ?? 3306);
    $database = trim($_POST['db_database'] ?? '');
    $username = trim($_POST['db_username'] ?? '');
    $password = $_POST['db_password'] ?? '';

    if (empty($host) || empty($database) || empty($username)) {
        $_SESSION['error'] = 'Please fill in all required fields.';
        redirect('?step=2');
    }

    try {
        // Test connection
        $dsn = "mysql:host=$host;port=$port;charset=utf8mb4";
        $pdo = new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);

        // Create database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$database` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$database`");

        // Import schema
        $schemaFile = __DIR__ . '/database.sql';
        if (file_exists($schemaFile)) {
            $sql = file_get_contents($schemaFile);
            $pdo->exec($sql);
        }

        // Save to session for config
        $_SESSION['db_config'] = [
            'host' => $host,
            'port' => $port,
            'database' => $database,
            'username' => $username,
            'password' => $password,
        ];

        $_SESSION['success'] = 'Database configured successfully!';
        redirect('?step=3');

    } catch (PDOException $e) {
        $_SESSION['error'] = 'Database connection failed: ' . $e->getMessage();
        redirect('?step=2');
    }
}

function handleConfiguration(): void
{
    $appUrl = trim($_POST['app_url'] ?? '');
    $appSecret = trim($_POST['app_secret'] ?? '');

    if (empty($appUrl)) {
        $_SESSION['error'] = 'Please enter your application URL.';
        redirect('?step=3');
    }

    // Generate secret if empty
    if (empty($appSecret)) {
        $appSecret = bin2hex(random_bytes(32));
    }

    $_SESSION['app_config'] = [
        'url' => rtrim($appUrl, '/'),
        'secret' => $appSecret,
    ];

    $_SESSION['success'] = 'Configuration saved!';
    redirect('?step=4');
}

function handleTelegramSetup(): void
{
    $botToken = trim($_POST['bot_token'] ?? '');
    $botUsername = trim($_POST['bot_username'] ?? '');

    if (empty($botToken)) {
        $_SESSION['error'] = 'Please enter your bot token.';
        redirect('?step=4');
    }

    // Validate bot token
    $response = @file_get_contents("https://api.telegram.org/bot$botToken/getMe");
    if (!$response) {
        $_SESSION['error'] = 'Invalid bot token. Please check and try again.';
        redirect('?step=4');
    }

    $data = json_decode($response, true);
    if (!($data['ok'] ?? false)) {
        $_SESSION['error'] = 'Bot token validation failed.';
        redirect('?step=4');
    }

    // Use username from API if not provided
    if (empty($botUsername)) {
        $botUsername = $data['result']['username'] ?? '';
    }

    $_SESSION['telegram_config'] = [
        'token' => $botToken,
        'username' => $botUsername,
    ];

    // Generate configuration file
    generateConfigFile();

    $_SESSION['success'] = 'Installation complete!';
    redirect('?step=5');
}

function generateConfigFile(): void
{
    $db = $_SESSION['db_config'] ?? [];
    $app = $_SESSION['app_config'] ?? [];
    $telegram = $_SESSION['telegram_config'] ?? [];

    $config = <<<PHP
<?php
/**
 * TON AI Agent - Configuration File
 * Generated by installer on {date}
 */

// Prevent direct access
if (basename(\$_SERVER['PHP_SELF']) === basename(__FILE__)) {
    http_response_code(403);
    exit('Direct access forbidden');
}

return [
    'app' => [
        'name' => 'TON AI Agent',
        'version' => '1.0.0',
        'env' => 'production',
        'debug' => false,
        'url' => '{app_url}',
        'timezone' => 'UTC',
        'secret_key' => '{app_secret}',
    ],

    'database' => [
        'driver' => 'mysql',
        'host' => '{db_host}',
        'port' => {db_port},
        'database' => '{db_database}',
        'username' => '{db_username}',
        'password' => '{db_password}',
        'charset' => 'utf8mb4',
        'collation' => 'utf8mb4_unicode_ci',
        'prefix' => 'taa_',
        'options' => [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ],
    ],

    'telegram' => [
        'bot_token' => '{telegram_token}',
        'bot_username' => '{telegram_username}',
        'webhook_secret' => '{webhook_secret}',
        'mini_app_url' => '{app_url}/app',
        'verify_signature' => true,
    ],

    'ton' => [
        'network' => 'mainnet',
        'rpc_endpoint' => 'https://toncenter.com/api/v2/jsonRPC',
        'api_key' => '',
        'wallet_version' => 'v4r2',
    ],

    'ai' => [
        'default_provider' => 'groq',
        'providers' => [
            'groq' => [
                'api_key' => '',
                'model' => 'llama-3.1-70b-versatile',
                'max_tokens' => 4096,
            ],
            'openai' => [
                'api_key' => '',
                'model' => 'gpt-4-turbo-preview',
                'max_tokens' => 4096,
            ],
            'anthropic' => [
                'api_key' => '',
                'model' => 'claude-3-opus-20240229',
                'max_tokens' => 4096,
            ],
        ],
        'server_side_only' => true,
    ],

    'security' => [
        'csrf' => [
            'enabled' => true,
            'token_name' => '_csrf_token',
            'token_length' => 32,
        ],
        'rate_limit' => [
            'enabled' => true,
            'max_requests' => 60,
            'time_window' => 60,
        ],
        'session' => [
            'name' => 'TAASESSID',
            'lifetime' => 7200,
            'secure' => true,
            'httponly' => true,
            'samesite' => 'Strict',
        ],
        'csp' => [
            'enabled' => true,
            'directives' => [
                'default-src' => "'self'",
                'script-src' => "'self' 'unsafe-inline' https://telegram.org",
                'style-src' => "'self' 'unsafe-inline' https://fonts.googleapis.com",
                'font-src' => "'self' https://fonts.gstatic.com",
                'img-src' => "'self' data: https:",
                'connect-src' => "'self' https://api.telegram.org https://toncenter.com",
            ],
        ],
    ],

    'logging' => [
        'enabled' => true,
        'level' => 'info',
        'path' => __DIR__ . '/../logs',
        'max_files' => 30,
    ],

    'cache' => [
        'driver' => 'file',
        'path' => __DIR__ . '/../cache',
        'ttl' => 3600,
        'prefix' => 'taa_cache_',
    ],

    'revenue' => [
        'performance_fee_percent' => 15,
        'management_fee_percent' => 2,
        'platform_share' => 30,
        'min_withdrawal' => 10,
    ],

    'premium' => [
        'tiers' => [
            'basic' => ['price' => 0, 'max_agents' => 1],
            'pro' => ['price' => 29, 'max_agents' => 5],
            'institutional' => ['price' => 299, 'max_agents' => 50],
        ],
    ],

    'localization' => [
        'default_locale' => 'en',
        'supported_locales' => ['en', 'ru', 'zh'],
        'fallback_locale' => 'en',
    ],
];
PHP;

    $webhookSecret = bin2hex(random_bytes(32));

    $config = str_replace(
        [
            '{date}',
            '{app_url}',
            '{app_secret}',
            '{db_host}',
            '{db_port}',
            '{db_database}',
            '{db_username}',
            '{db_password}',
            '{telegram_token}',
            '{telegram_username}',
            '{webhook_secret}',
        ],
        [
            date('Y-m-d H:i:s'),
            $app['url'] ?? '',
            $app['secret'] ?? '',
            $db['host'] ?? 'localhost',
            $db['port'] ?? 3306,
            $db['database'] ?? 'tonaiagent',
            $db['username'] ?? '',
            addslashes($db['password'] ?? ''),
            $telegram['token'] ?? '',
            $telegram['username'] ?? '',
            $webhookSecret,
        ],
        $config
    );

    // Write config file
    $configPath = __DIR__ . '/app/config.php';
    file_put_contents($configPath, $config);
    chmod($configPath, 0600);

    // Create logs and cache directories
    $dirs = [__DIR__ . '/logs', __DIR__ . '/cache'];
    foreach ($dirs as $dir) {
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
    }
}

function redirect(string $url): void
{
    header("Location: $url");
    exit;
}

function checkRequirements(): array
{
    $requirements = [];

    // PHP Version
    $requirements['php_version'] = [
        'name' => 'PHP Version',
        'required' => '8.0+',
        'current' => PHP_VERSION,
        'pass' => version_compare(PHP_VERSION, '8.0.0', '>='),
    ];

    // PDO MySQL
    $requirements['pdo_mysql'] = [
        'name' => 'PDO MySQL Extension',
        'required' => 'Enabled',
        'current' => extension_loaded('pdo_mysql') ? 'Enabled' : 'Disabled',
        'pass' => extension_loaded('pdo_mysql'),
    ];

    // cURL
    $requirements['curl'] = [
        'name' => 'cURL Extension',
        'required' => 'Enabled',
        'current' => extension_loaded('curl') ? 'Enabled' : 'Disabled',
        'pass' => extension_loaded('curl'),
    ];

    // JSON
    $requirements['json'] = [
        'name' => 'JSON Extension',
        'required' => 'Enabled',
        'current' => extension_loaded('json') ? 'Enabled' : 'Disabled',
        'pass' => extension_loaded('json'),
    ];

    // OpenSSL
    $requirements['openssl'] = [
        'name' => 'OpenSSL Extension',
        'required' => 'Enabled',
        'current' => extension_loaded('openssl') ? 'Enabled' : 'Disabled',
        'pass' => extension_loaded('openssl'),
    ];

    // Mbstring
    $requirements['mbstring'] = [
        'name' => 'Mbstring Extension',
        'required' => 'Enabled',
        'current' => extension_loaded('mbstring') ? 'Enabled' : 'Disabled',
        'pass' => extension_loaded('mbstring'),
    ];

    // Writable directories
    $appDir = __DIR__ . '/app';
    $requirements['app_writable'] = [
        'name' => 'App Directory Writable',
        'required' => 'Writable',
        'current' => is_writable($appDir) ? 'Writable' : 'Not Writable',
        'pass' => is_writable($appDir),
    ];

    return $requirements;
}

$allPassed = true;
if ($currentStep === 1) {
    $requirements = checkRequirements();
    foreach ($requirements as $req) {
        if (!$req['pass']) {
            $allPassed = false;
            break;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TON AI Agent - Installer</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #0088CC, #1a1a2e);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .installer {
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.2);
            max-width: 600px;
            width: 100%;
            overflow: hidden;
        }
        .header {
            background: #0088CC;
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 { font-size: 24px; margin-bottom: 8px; }
        .header p { opacity: 0.9; }
        .steps {
            display: flex;
            padding: 20px;
            background: #f8f9fa;
            border-bottom: 1px solid #e9ecef;
        }
        .step {
            flex: 1;
            text-align: center;
            position: relative;
        }
        .step-num {
            width: 32px;
            height: 32px;
            border-radius: 50%;
            background: #e9ecef;
            color: #6c757d;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            font-weight: 600;
            margin-bottom: 4px;
        }
        .step.active .step-num { background: #0088CC; color: white; }
        .step.completed .step-num { background: #28a745; color: white; }
        .step-label { font-size: 12px; color: #6c757d; }
        .content { padding: 30px; }
        .form-group { margin-bottom: 20px; }
        .form-group label { display: block; font-weight: 500; margin-bottom: 8px; color: #333; }
        .form-group input {
            width: 100%;
            padding: 12px;
            border: 1px solid #ddd;
            border-radius: 8px;
            font-size: 14px;
        }
        .form-group input:focus { outline: none; border-color: #0088CC; }
        .form-group small { color: #6c757d; font-size: 12px; margin-top: 4px; display: block; }
        .btn {
            display: inline-block;
            padding: 12px 24px;
            background: #0088CC;
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 600;
            cursor: pointer;
            text-decoration: none;
        }
        .btn:hover { background: #006699; }
        .btn:disabled { background: #ccc; cursor: not-allowed; }
        .btn-outline { background: white; color: #0088CC; border: 1px solid #0088CC; }
        .requirements { margin-bottom: 20px; }
        .requirement {
            display: flex;
            justify-content: space-between;
            padding: 12px;
            border-bottom: 1px solid #e9ecef;
        }
        .requirement:last-child { border-bottom: none; }
        .requirement .name { font-weight: 500; }
        .requirement .status { font-size: 14px; }
        .requirement .status.pass { color: #28a745; }
        .requirement .status.fail { color: #dc3545; }
        .alert {
            padding: 12px 16px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .alert-error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        .alert-success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .complete-icon {
            width: 80px;
            height: 80px;
            background: #28a745;
            border-radius: 50%;
            margin: 0 auto 20px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .complete-icon svg { width: 40px; height: 40px; fill: white; }
        .warning { background: #fff3cd; color: #856404; padding: 16px; border-radius: 8px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="installer">
        <div class="header">
            <h1>TON AI Agent</h1>
            <p>Installation Wizard</p>
        </div>

        <div class="steps">
            <?php foreach ($steps as $num => $label): ?>
            <div class="step <?= $num < $currentStep ? 'completed' : ($num === $currentStep ? 'active' : '') ?>">
                <div class="step-num"><?= $num < $currentStep ? '✓' : $num ?></div>
                <div class="step-label"><?= $label ?></div>
            </div>
            <?php endforeach; ?>
        </div>

        <div class="content">
            <?php if ($error): ?>
            <div class="alert alert-error"><?= htmlspecialchars($error) ?></div>
            <?php endif; ?>

            <?php if ($success): ?>
            <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
            <?php endif; ?>

            <?php if ($currentStep === 1): ?>
            <!-- Step 1: Requirements Check -->
            <h2 style="margin-bottom: 20px;">System Requirements</h2>
            <div class="requirements">
                <?php foreach ($requirements as $req): ?>
                <div class="requirement">
                    <div>
                        <div class="name"><?= $req['name'] ?></div>
                        <small>Required: <?= $req['required'] ?></small>
                    </div>
                    <div class="status <?= $req['pass'] ? 'pass' : 'fail' ?>">
                        <?= $req['current'] ?> <?= $req['pass'] ? '✓' : '✗' ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <?php if ($allPassed): ?>
            <a href="?step=2" class="btn">Continue →</a>
            <?php else: ?>
            <button class="btn" disabled>Fix Requirements First</button>
            <?php endif; ?>

            <?php elseif ($currentStep === 2): ?>
            <!-- Step 2: Database Setup -->
            <h2 style="margin-bottom: 20px;">Database Configuration</h2>
            <form method="POST">
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" name="db_host" id="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label for="db_port">Database Port</label>
                    <input type="number" name="db_port" id="db_port" value="3306" required>
                </div>
                <div class="form-group">
                    <label for="db_database">Database Name</label>
                    <input type="text" name="db_database" id="db_database" value="tonaiagent" required>
                    <small>Will be created if it doesn't exist</small>
                </div>
                <div class="form-group">
                    <label for="db_username">Database Username</label>
                    <input type="text" name="db_username" id="db_username" required>
                </div>
                <div class="form-group">
                    <label for="db_password">Database Password</label>
                    <input type="password" name="db_password" id="db_password">
                </div>
                <button type="submit" class="btn">Test & Continue →</button>
            </form>

            <?php elseif ($currentStep === 3): ?>
            <!-- Step 3: Configuration -->
            <h2 style="margin-bottom: 20px;">Application Configuration</h2>
            <form method="POST">
                <div class="form-group">
                    <label for="app_url">Application URL</label>
                    <input type="url" name="app_url" id="app_url" placeholder="https://your-domain.com" required>
                    <small>Your Mini App will be accessible at this URL</small>
                </div>
                <div class="form-group">
                    <label for="app_secret">Application Secret (Optional)</label>
                    <input type="text" name="app_secret" id="app_secret" placeholder="Leave empty to auto-generate">
                    <small>Used for encryption and security tokens</small>
                </div>
                <button type="submit" class="btn">Continue →</button>
            </form>

            <?php elseif ($currentStep === 4): ?>
            <!-- Step 4: Telegram Bot -->
            <h2 style="margin-bottom: 20px;">Telegram Bot Setup</h2>
            <p style="margin-bottom: 20px;">Create a bot with @BotFather and get your bot token.</p>
            <form method="POST">
                <div class="form-group">
                    <label for="bot_token">Bot Token</label>
                    <input type="text" name="bot_token" id="bot_token" placeholder="123456789:ABCdefGHI..." required>
                    <small>Get this from @BotFather on Telegram</small>
                </div>
                <div class="form-group">
                    <label for="bot_username">Bot Username (Optional)</label>
                    <input type="text" name="bot_username" id="bot_username" placeholder="@your_bot">
                    <small>Auto-detected from bot token if left empty</small>
                </div>
                <button type="submit" class="btn">Complete Installation →</button>
            </form>

            <?php elseif ($currentStep === 5): ?>
            <!-- Step 5: Complete -->
            <div style="text-align: center;">
                <div class="complete-icon">
                    <svg viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>
                </div>
                <h2>Installation Complete!</h2>
                <p style="margin: 16px 0; color: #666;">TON AI Agent has been successfully installed.</p>

                <div style="text-align: left; margin: 20px 0;">
                    <h3 style="margin-bottom: 12px;">Next Steps:</h3>
                    <ol style="margin-left: 20px; line-height: 1.8;">
                        <li>Set up your Telegram Bot Web App URL in @BotFather</li>
                        <li>Configure AI API keys in <code>app/config.php</code></li>
                        <li>Set up webhook: <code><?= $_SESSION['app_config']['url'] ?? '' ?>/webhook</code></li>
                        <li><strong>Delete this installer file!</strong></li>
                    </ol>
                </div>

                <a href="/" class="btn">Open Mini App</a>

                <div class="warning">
                    <strong>⚠️ Security Warning:</strong> Please delete <code>install.php</code> from your server now to prevent unauthorized access.
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
